app = 'human-backend'
primary_region = 'ewr'

[build]
  dockerfile = "docker/app/Dockerfile"
  build_context = "."

[env]
  PORT = '8080'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
