# Generated by Django 4.2.2 on 2023-07-10 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('criticalevents', '0002_incidentreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=15, max_digits=18)),
                ('longitude', models.DecimalField(decimal_places=15, max_digits=18)),
            ],
        ),
        migrations.CreateModel(
            name='MessageReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twilio_message_id', models.CharField(max_length=50)),
                ('body', models.TextField(max_length=500)),
                ('sender_phone', models.CharField(max_length=20)),
                ('recipient_phone', models.CharField(max_length=20)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='criticalevents.incidentreport')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='criticalevents.person')),
            ],
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='criticalevents.location'),
        ),
    ]
