# Generated by Django 4.2.2 on 2023-07-18 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('criticalevents', '0003_location_messagereceipt_incidentreport_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('body', models.TextField(max_length=500)),
                ('incident_report', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='criticalevents.incidentreport')),
            ],
        ),
    ]
