# Generated by Django 4.2.2 on 2024-04-24 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("criticalevents", "0004_rename_assettypes_assettype"),
    ]

    operations = [
        migrations.AddField(
            model_name="assettype",
            name="icon_identifier",
            field=models.CharField(default="fire-extinguisher", max_length=255),
        ),
    ]
