# Generated by Django 4.2.2 on 2023-07-18 08:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('criticalevents', '0005_alter_alert_incident_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='sender',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
