# Generated by Django 4.2.2 on 2024-04-25 22:28

import criticalevents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("criticalevents", "0005_assettype_icon_identifier"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to=criticalevents.models.asset_upload_to
            ),
        ),
        migrations.AlterField(
            model_name="floor",
            name="floor_plan",
            field=models.ImageField(
                upload_to=criticalevents.models.floor_plan_upload_to
            ),
        ),
        migrations.AlterField(
            model_name="site",
            name="floor_plan",
            field=models.ImageField(
                upload_to=criticalevents.models.floor_plan_upload_to
            ),
        ),
    ]
