# Generated by Django 4.2.2 on 2023-07-20 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('criticalevents', '0007_personstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentreport',
            name='resolved_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='personstatus',
            name='incident_report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='statuses', to='criticalevents.incidentreport'),
        ),
    ]
