# Generated by Django 4.2.2 on 2024-04-25 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("criticalevents", "0007_maintenancelog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="maintenancelog",
            name="notes",
            field=models.TextField(max_length=2000),
        ),
    ]
