# Generated by Django 4.2.2 on 2023-07-20 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('criticalevents', '0008_incidentreport_resolved_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personstatus',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='criticalevents.person'),
        ),
    ]
