# Generated by Django 4.2.2 on 2024-05-02 00:32

import criticalevents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("criticalevents", "0008_alter_maintenancelog_notes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="site",
            name="floor_plan",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=criticalevents.models.floor_plan_upload_to,
            ),
        ),
        migrations.AlterField(
            model_name="site",
            name="floor_plan_bounds",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
