# Generated by Django 4.2.2 on 2024-05-02 17:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("criticalevents", "0009_alter_site_floor_plan_alter_site_floor_plan_bounds"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="next_maintenance_date",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
