# Generated by Django 4.2.2 on 2023-11-20 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('criticalevents', '0009_alter_personstatus_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=10)),
                ('incident_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='short_tokens', to='criticalevents.incidentreport')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='short_tokens', to='criticalevents.person')),
            ],
        ),
    ]
