# Generated by Django 4.2.2 on 2024-04-18 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criticalevents', '0011_site'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='location',
        ),
        migrations.AddField(
            model_name='site',
            name='latitude',
            field=models.DecimalField(decimal_places=15, default=40, max_digits=18),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='longitude',
            field=models.DecimalField(decimal_places=15, default=40, max_digits=18),
            preserve_default=False,
        ),
    ]
