# Generated by Django 4.2.2 on 2024-05-02 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("criticalevents", "0011_alter_asset_next_maintenance_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="maintenancelog",
            name="reported_by",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.RESTRICT,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
