# Generated by Django 4.2.2 on 2024-05-09 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("criticalevents", "0012_maintenancelog_reported_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="site",
            name="bounds",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
