# Generated by Django 4.2.2 on 2024-05-13 22:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("criticalevents", "0013_alter_site_bounds"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="managed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
